### ISSUE TITLE
Some PDF configurations are not compiling

### ISSUE THREAD

**Issue by AFOliveira** [riscv-software-src/riscv-unified-db#106]
Just to keep track of this problem, there's an error in PDF generation that happens to some extensions. It was caused by a back-end update.
At least, it affects the I extension.

**Comment by jalobaba** [comment]
I'm curious what the issue is. Do you have more details?

**Comment by AFOliveira** [comment]
The problem happens when you try to run `./do gen:ext_pdf[I]` .
The error itself looks like this
![image](https://github.com/user-attachments/assets/8dcec8e4-0a52-4c13-bbe8-e99a27c474f7)

**Comment by james-ball-qualcomm** [comment]
Can you update the issue's title to make it clearer what the issue is related to?

**Comment by AFOliveira** [comment]
> Can you update the issue's title to make it clearer what the issue is related to?

Surely!  Sorry if it's not clear yet, feel free to make any suggestion or change it as you think it may be better.

**Comment by jalobaba** [comment]
Looks good now. Thanks!

**Comment by dhower-qc** [comment]
This is caused by the fact that the extension document generator isn't being careful to check that extension data (yaml files) have all the information it's expecting. I'm working on a patch now so that it won't crash, but long term, we just want to get all the data filled in the database.
