### ISSUE TITLE
Update CRD template to remove priviledge modes not present in MC-1

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#107]
![image](https://github.com/user-attachments/assets/16a8ab1c-613a-488d-8f6d-935e0a66402f)

**Comment by dhower-qc** [comment]
This isn't CRD-specific. That table comes out the cycle.yaml file.

**Comment by james-ball-qualcomm** [comment]
Duplicate of #178
