### ISSUE TITLE
Asciidoc leaking through in MISALIGNED_SPLIT_STRATEGY

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#109]
![image](https://github.com/user-attachments/assets/f0939351-769c-46ed-8862-5bb7dc225811)

**Comment by dhower-qc** [comment]
@james-ball-qualcomm, which document is this in? My guess is that we are including this in an asciidoc block type that isn't being parsed as asciidoc
