### ISSUE TITLE
ecall and ebreak are shown as not generating exceptions

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#112]
Exceptions are much improved for most instructions (e.g., none for add, a bunch for load). However, shouldn't ecall and ebreak generate exceptions? 

![image](https://github.com/user-attachments/assets/8b8e4d5d-763f-488e-8f05-e9ac5658323b)

**Comment by dhower-qc** [comment]
Why, yes they should ;) I'll take a look

**Comment by dhower-qc** [comment]
This one turned out to be simple; I added a raise_precise function in IDL to differentiate some exceptions that required to be precise. I did not, however, add have the exception checking pass look for calls to raise_precise.
