### ISSUE TITLE
Quad and Double precision registers

### ISSUE THREAD

**Issue by AFOliveira** [riscv-software-src/riscv-unified-db#151]
We describe floating point registers as "fs1" for floating-point, how should we do for Quad precision and double precision? qs1 and ds1? This would look odd on destination registers that would be presented as "dd" for doubles.

**Comment by AFOliveira** [comment]
@dhower-qc

**Comment by AFOliveira** [comment]
In #157 there's what I called them. Maybe fd and fq would be better, or do you prefer current naming?

**Comment by dhower-qc** [comment]
I think what you did looks great.
