### ISSUE TITLE
Missing description for mip CSR

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#176]
![image](https://github.com/user-attachments/assets/d957532d-eb3a-4d55-ab96-c4ed105e1509)

**Comment by dhower-qc** [comment]
It's not missing, it's just brief. The description is "Machine Interrupt Pending bits"

**Comment by james-ball-qualcomm** [comment]
Can we make it more descriptive then? Maybe move some of the content from mie to mip? Or at least tell people to look at mie's description (ideally with a link) if the intent is that mie's description covers both mie and mip?
