### ISSUE TITLE
Example YAML Comment/Feedback

### ISSUE THREAD

**Issue by dhower-qc** [riscv-software-src/riscv-unified-db#22]
@jjscheel:

Here is an example of attaching a comment to YAML using Github:

https://github.com/riscv-software-src/riscv-unified-db/blob/45fdc6ee3011d345d1f96c843e638a7284a32616/arch/inst/I/lb.yaml#L26

You can create this by clicking the three dots next to a line you want to comment on and selecting "Reference in new issue".

Additionally, a similar feature exists for any pull request, which is when most reviews will occur.

**Comment by jjscheel** [comment]
Ok.  So, comments will come in via GitHub.

That means the next discussion will be WHAT people will review.  I understand the final form may be YAML, but I suspect people will want something more consumable like a PDF, which means they'll have to manually map back to the YAML text to comment.

As I said in today's call, I'm not against this.  I'm just trying to make sure we've got the details ironed out as to how this will work.
