### ISSUE TITLE
Make name and kind explicit in objects

### ISSUE THREAD

**Issue by dhower-qc** [riscv-software-src/riscv-unified-db#246]
Need to update Ruby code, too.

**Comment by dhower-qc** [comment]
This reminds me of another issue I want to address. It would be good if all the YAML was passed through a rigid formatter before being checked in. That would let us, _e.g._, modify the data with scripts without producing unreadable diffs (since your programming language YAML library isn't going to spit out the data in the same order/format as it was read in). At minimum, I think we want all keys to be sorted alphabetically, and strings to be consistent depending on whether they are a single line or multiline.

I looked around for a YAML formatter that would work, but a cursory search didn't find anything. @drom, are you aware of anything? Worst case, I could cook up something basic.

**Comment by drom** [comment]
I know nothing about YAML , I mostly use JSON or JSON5
