### ISSUE TITLE
Change certificate models and profile releases use ~> for version numbers of extensions

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#289]
Was discussing this with @dlweaver today. I noticed that RVA20, RVA22, etc. profile releases specify some extension versions using = and some using ~>. For example, see screenshot. Seems like there are 2 use cases and in one case ~> is fine and in the other = is required: 

1. I want to see if an implementation is compliant with some profile release and so as long as it has extensions that are backwards compatible with the versions listed in the profile release, I'm good. In this case we want to use ~> to allow newer versions that are backwards compatible.
2. I want to see which the version of each extension in a profile release when that release was made. In this case, I want = so I can see exactly the snapshot of the extension versions. 

If for case #2 above if the ~> version number matches the version number of each extension when the profile release was ratified, then we'd be able to cover both cases if we use ~>. So, that begs the question why aren't *all* the version numbers in a profile release using ~>? Why are some = and some ~>?

![image](https://github.com/user-attachments/assets/281311b3-db2e-4240-a82b-546f9f34d770)

**Comment by dhower-qc** [comment]
This inconsistency exists because I'm not sure what a profile actually means. It _should_ be all `~>` or all `=`, I'm just not sure which one.

If it's `~>`, then we mean that a profile is specifying a range of (presumably compatible) extension versions. If it's `=`, then we mean that a profile specifies exactly one extension version.

The ratified profile specs don't mention versions, which is why this is ambiguous.

**Comment by james-ball-qualcomm** [comment]
A profile or certificate should all be ~> since it documents what an implementation must provide to be compliant. So, any updated backwards compatible extension is compliant. So, we should change all of these in existing certificates and profiles. I can do that.
