### ISSUE TITLE
Support XLEN as a parameter for certificates

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#290]
Currently XLEN has to be restricted to just being 32 or 64 in an certificate's model YAML file and is used by the certificate rakefile. I'd like to have MC100 support being either a 32-bit or 64-bit microcontroller since that is easy for us to certify. However, this isn't currently allowed. I can work on this but will need assistance.

![image](https://github.com/user-attachments/assets/7ffe6d10-18c6-4c7e-9608-e1c29e39e32d)

**Comment by dhower-qc** [comment]
I believe we decided to have a cert per MXLEN
