### ISSUE TITLE
Incorrect syntax for some instructions' "definedBy" extensions

### ISSUE THREAD

**Issue by ThinkOpenly** [riscv-software-src/riscv-unified-db#319]
Some instructions' "definedBy" fields appear to be incorrect, using an open comma-separated list, rather than a subfield refinement with "allOf".
```
./arch/inst/F/fmaxm.s.yaml:definedBy: F, Zfa
./arch/inst/F/froundnx.s.yaml:definedBy: F, Zfa
./arch/inst/F/fround.s.yaml:definedBy: F, Zfa
./arch/inst/F/fltq.s.yaml:definedBy: F, Zfa
./arch/inst/F/fleq.s.yaml:definedBy: F, Zfa
./arch/inst/F/fli.s.yaml:definedBy: F, Zfa
./arch/inst/F/fminm.s.yaml:definedBy: F, Zfa
```

I think each of these should be expanded to:
```
definedBy:
  allOf:
  - F
  - Zfa
```

Although, since Unpriv spec Version 20240411 says:
> The Zfa extension depends on the F extension

maybe only the Zfa extension needs to be called out as the "definedBy" extension?

**Comment by AFOliveira** [comment]
This is indeed true and those instructions are missing on the output manual. I'll fix this ASAP. @dhower-qc Do you think  it is worth it to add a test on this to the smoke tests?

**Comment by dhower-qc** [comment]
> Do you think it is worth it to add a test on this to the smoke tests?

definitely!!
