### ISSUE TITLE
Add missing extensions

### ISSUE THREAD

**Issue by ThinkOpenly** [riscv-software-src/riscv-unified-db#320]
I wrote a script that looked for references to extensions for which there was no corresponding extension definition. The following extensions are referenced, but have no definition:

- Q
- Smrnmi
- Zalasr
- Zfa
- Zfbfmin
- Zfh
- Zicond
- Zimop
- Zvfbfmin
- Zvfbfwma
- Zvkg

The script also found these, but there are issues open for adding them already:
- Smdbltrp
- Zabha
- Zacas
- Zawrs
- Sdext

(This script could be a good thing to add to CI, I suppose.)

**Comment by ThinkOpenly** [comment]
And, my script missed some extensions that are referenced, but not defined. I think adding these completes the set:
- Zbkb
- Zbkc
- Zbkx
- Zbp
- Zca
- Zk
- Zkn
- Zknd
- Zkne
- Zknh
- Zks
- Zksed
- Zksh
- Zvbb
- Zvbc
- Zvkn
- Zvkned
- Zvknha
- Zvknhb
- Zvks
- Zvksed
- Zvksh

**Comment by james-ball-qualcomm** [comment]
Ssu64xl is also missing. Defined by RVA20 profile. I'm adding it in #332.

I also will be adding these since they are needed for RVA22:
- Zfh
- Zkn
- Zks
