### ISSUE TITLE
C extensions have improperly formatted adoc descriptions

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#326]
Seeing lots of messages like this when generating MC100-32 PDF:

asciidoctor: ERROR: failed to parse formatted text: C.ADDI adds the non-zero sign-extended 6-bit immediate to the value in register rd then writes the result to rd. C.ADDI expands into <code>addi rd, rd, imm</code>. C.ADDI is only valid when rd &ne; x0 and imm &ne; 0. The code points with rd=x0 encode the C.NOP instruction; the remaining code points with imm=0 encode HINTs. (reason: Expected one of '#', '#x', 'amp', 'apos', 'gt', 'lt', 'nbsp', 'quot' after & at byte 195)

**Comment by dhower-qc** [comment]
Let's table this for now; it should be addressed by a bigger push to link the ISA manual with tags
