### ISSUE TITLE
The sail code description for add.yaml contains other instructions operations as well

### ISSUE THREAD

**Issue by MuhammadHammad001** [riscv-software-src/riscv-unified-db#330]
Hi @dhower-qc  @james-ball-qualcomm , I hope you both are doing great.
I am currently exploring this tool and was going through the files. I realized that the sail code for add instruction contains the expected operations for other instructions as well like slt, stlu, ... available [here](https://github.com/riscv-software-src/riscv-unified-db/blob/main/arch/inst/I/add.yaml).

Please let me know if I have mis-understood the format as I am still learning !
 
**Current value and location** 
I have included just the target code to be replaced.
```
sail(): |
  {
    let rs1_val = X(rs1);
    let rs2_val = X(rs2);
    let result : xlenbits = match op {
      RISCV_ADD  => rs1_val + rs2_val,
      RISCV_SLT  => zero_extend(bool_to_bits(rs1_val <_s rs2_val)),
      RISCV_SLTU => zero_extend(bool_to_bits(rs1_val <_u rs2_val)),
      RISCV_AND  => rs1_val & rs2_val,
      RISCV_OR   => rs1_val | rs2_val,
      RISCV_XOR  => rs1_val ^ rs2_val,
      RISCV_SLL  => if   sizeof(xlen) == 32
                    then rs1_val << (rs2_val[4..0])
                    else rs1_val << (rs2_val[5..0]),
      RISCV_SRL  => if   sizeof(xlen) == 32
                    then rs1_val >> (rs2_val[4..0])
                    else rs1_val >> (rs2_val[5..0]),
      RISCV_SUB  => rs1_val - rs2_val,
      RISCV_SRA  => if   sizeof(xlen) == 32
                    then shift_right_arith32(rs1_val, rs2_val[4..0])
                    else shift_right_arith64(rs1_val, rs2_val[5..0])
    };
    X(rd) = result;
    RETIRE_SUCCESS
  }
```
Where is this data?
[here](https://github.com/riscv-software-src/riscv-unified-db/blob/main/arch/inst/I/add.yaml)
**Expected value**
What do you think the value(s) should be? 
(sorry for syntax errors as I don't have much idea about Sail Language yet! )
```
sail():
  let rs1_val = X(rs1);
  let rs2_val = X(rs2);
  let result : xlenbits = rs1_val + rs2_val;
  X(rd) = result;
  RETIRE_SUCCESS
```

**Comment by dhower-qc** [comment]
This is directly copied from the Sail model using a tool @ThinkOpenly has developed. I think in order to change it, we would need to refactor the Sail model.
