### ISSUE TITLE
Accidental files?

### ISSUE THREAD

**Issue by dhower-qc** [riscv-software-src/riscv-unified-db#48]
https://github.com/riscv-software-src/riscv-unified-db/blob/b92b19fdef8fdaa1ceaae3fbd53527e6fc4e14a5/rva.pdf%3AAvecto.Zone.Identifier#L1

I assume rva.pdf:Avecto.Zone.Identifier and rva.pdf:Zone.Identifier are not supposed to be checked in?

**Comment by james-ball-qualcomm** [comment]
I was wondering what those were. I'll remove them. And I assume I should update the git file that says to ignore them in the future.

**Comment by james-ball-qualcomm** [comment]
Actually, they were created by Windows when I copied a pre-built PDF into the top of the git tree.
