### ISSUE TITLE
C extension YAML references tables not present

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#50]
I see this when building the MC-1 CRD since it includes the C extension:

asciidoctor: INFO: possible invalid reference: rvc-instr-table0
asciidoctor: INFO: possible invalid reference: rvc-instr-table0
asciidoctor: INFO: possible invalid reference: rvc-instr-table0
asciidoctor: INFO: possible invalid reference: rvc-instr-table0

This is the Table34 issue we looked at the other day.

**Comment by dhower-qc** [comment]
closing; this will get handled by a larger documentation strategy
