### ISSUE TITLE
Can't find riscv-unified-db HTML anymore

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#51]
https://riscv-software-src.github.io/riscv-unified-db/manual/index.html

404 Error

**Comment by dhower-qc** [comment]
It moved to https://riscv-software-src.github.io/riscv-unified-db/manual/html/index.html

**Comment by kbroch-rivosinc** [comment]
@dhower-qc : I think it would useful to edit the "About" section of the project and add this link as the "website" as it's hard to track down otherwise.
