### ISSUE TITLE
Generated IDL in CRD appendix says "%%LINK%%" instead of correct value (like I see in the Profile).

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#56]
![image](https://github.com/user-attachments/assets/d4bfe6de-5b20-4995-901b-5d1769bed2a9)

**Comment by dhower-qc** [comment]
You'll need to run the asciidoc through resolve_links while generating. See:

https://github.com/riscv-software-src/riscv-unified-db/blob/c02ef47612d60541997865132ed2501850a0a7b0/backends/profile_doc/tasks.rake#L25

**Comment by james-ball-qualcomm** [comment]
Fixed now.
