### ISSUE TITLE
CRD CSR appendix has PMP registers

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#57]
Looks like these CSRs are included even if the PMP isn't present. Should we create an extension name for the PMP for the database?

![image](https://github.com/user-attachments/assets/0b27d77c-415a-498e-83b1-88c0570877f5)

**Comment by dhower-qc** [comment]
I believe this is being done by @james-ball-qualcomm

**Comment by dhower-qc** [comment]
fixed in #68
