### ISSUE TITLE
All hpmcounters have a long name saying "Cycle counter for RDCYCLE Instruction" and Ruby template code shows up in PDF

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#70]
![image](https://github.com/user-attachments/assets/918f07c7-7174-4bcd-bbac-21dc20fc4b72)

**Comment by dhower-qc** [comment]
fixed in 1dd5ef0a61598cdab22c05d7b3a78e726bb167f9, part of #68
