### ISSUE TITLE
Why are there both ArchDef and ArchDefObject classes?

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#75]
Looks like the ArchDef class contains Ruby objects from the database of class containing the "database" of RISC-V standards including extensions, instructions, parameters, CSRs, Profiles, and CRDs. Many classes have an ArchDef class reference called "archdef".

Then there is the ArchDefObject class which provides facilities for accessing the contents of a related objects YAML file via the "data" member (hash holding YAML file contents).

Looks like the backend templates for CRDs are provided with a reference to a Crd class object which has access to the "data" hash and pulls it out when the backend runs.

I've always imagined the database would parse the YAML files into Ruby objects and then the various backends would use those Ruby objects (as an IR) and only have access to the objects (and not the file that was parsed to create the Ruby objects).

Let's talk about this first before you write an answer here since I imagine this will be an interactive discussion.

**Comment by dhower-qc** [comment]
ArchDef is the view of the database + any known configuration parameters. ArchDefObject is the base class of an object in the database, e.g., an Instruction, an Extension, a Profile, etc.
