### ISSUE TITLE
Does riscv-unified-db contain information about MCAUSE interrupt ID assignments?

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#91]
The db has information about several address spaces (opcodes, CSRs, etc). I think I've found another candidate: IRQ assignments.

Here's info from the CLIC spec related to this:

`ID  Interrupt   Note

 0  reserved
 1  ssip        Supervisor software Interrupt
 2  reserved
 3  msip        Machine software interrupt

 4  reserved
 5  stip        Supervisor timer interrupt
 6  reserved
 7  mtip        Machine timer interrupt

 8  reserved
 9  seip        Supervisor external (PLIC/APLIC) interrupt
10  reserved
11  meip        Machine external (PLIC/APLIC) interrupt

12  reserved
13  reserved
14  reserved
15  reserved

16  csip        CLIC software interrupt
17+ inputs      CLIC local inputs`

**Comment by dhower-qc** [comment]
That's already there.

https://github.com/riscv-software-src/riscv-unified-db/blob/00213d2b2703240dc4fbe90dcdd8749e5b5f7e35/arch/ext/Sm.yaml#L108-L125
